name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 backend

      - name: Type check with mypy
        run: |
          pip install mypy
          mypy backend

      - name: Run tests
        run: pip install pytest && pytest --maxfail=3 --disable-warnings -q -v

      - name: Build Docker Compose
        run: docker-compose build

      - name: Smoke test backend
        run: |
          docker-compose up -d app
          sleep 10
          curl --fail http://localhost:3012/metrics
          curl --fail -X POST http://localhost:3012/query -d '{"messages":[{"role":"user","content":"ping"}]}' || exit 1
          docker-compose down

      - name: Upload coverage to Codecov
        if: success() && github.event_name != 'pull_request'
        uses: codecov/codecov-action@v3
