name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install --upgrade pip && pip install -r requirements.txt

      - name: Run tests
        run: pip install pytest && pytest --maxfail=2 --disable-warnings -q -v

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1
        with:
          version: latest

      - name: Build services
        run: docker compose build

      - name: Start app
        run: docker compose up -d app

      - name: Dump app logs
        run: docker compose logs rag_app

      - name: Wait for app readiness
        run: |
          for i in {1..30}; do
            if curl --fail http://localhost:3012/metrics; then break; fi
            echo "waiting…"
            sleep 2
          done

      - name: Smoke test backend
        run: |
          curl --fail http://localhost:3012/metrics
          curl --fail -X POST http://localhost:3012/query \
            -H "Content-Type: application/json" \
            -d '{"messages":[{"role":"user","content":"ping"}]}'

      - name: Teardown
        if: always()
        run: docker compose down

      - name: Upload coverage to Codecov
        if: success() && github.event_name != 'pull_request'
        uses: codecov/codecov-action@v3
